apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnb-du-deployment
  labels:
    app: gnb-du
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnb-du
  template:
    metadata:
      labels:
        app: gnb-du
    spec:
      containers:
      - name: gnb-du-container
        image: oaisoftwarealliance/oai-gnb:develop
        securityContext:
          privileged: true
        env:
        - name: USE_ADDITIONAL_OPTIONS
          value: "--sa --rfsim --log_config.global_log_options level,nocolor,time,line_num,function"
        volumeMounts:
        - name: gnb-du-config-volume
          mountPath: /opt/oai-gnb/etc/gnb.conf
          #subPath: gnb-du.sa.band78.106prb.rfsim.conf
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "pgrep nr-softmodem"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: gnb-du-config-volume
        hostPath:
          path: /home/priyanshu/Desktop/k8s_cluster/gnb-du.sa.band78.106prb.rfsim.conf  # Replace with correct path
          type: File
      hostNetwork: true